### PR TITLE
global style clean up

### PR DESCRIPTION
**Pull request by zebapy**
First wave of changes to deploy for #75 

Merging this into master from dev so the changes are "frozen" so they can be implemented on drupal repo.

### CODE REVIEW

**Comment by imcbride** [comment]
In addition to the Related Stories / Events types you've included, there is also a paragraph for "Related Stories - Program" and "Related Events - Program". I can forward you information on the markup that these currently use, if that would be helpful.

**Comment by zebapy** [comment]
Do their fields vary?

**Comment by imcbride** [comment]
The paragraphs have the same fields: title, call to action, and tag (the program to list events/stories from), however they are currently configured to show slightly different forms of the content. The Related Stories - Program list uses the Teaser display https://github.com/middlebury/drupal8/blob/master/themes/custom/institute_theme/templates/content/node--story--teaser.html.twig while the Related Events - Program paragraph uses the Related display https://github.com/middlebury/drupal8/blob/master/themes/custom/institute_theme/templates/content/node--event--related.html.twig.

**Comment by zebapy** [comment]
Ok. I'm tracking what's done here https://github.com/middlebury/frontend/issues/75 if you want to move discussion there or add any items to the list. 

Since the `story-teaser` component is updated, does that not cover Related Stories - Programs? 

As for the `card` components, I have yet to do those.

**Comment by imcbride** [comment]
Using the card components to list the related events on the program pages is probably wrong and a result of the config being very out-of-date with how we've developed the site.

Making each of these components a list of teasers would work for the program pages, I just wanted to call it out since I had neglected to mention it earlier, so I could give you and Ari a chance to change how that component is shown on the program page, if you wish.

**Pull request merged**
